### ISSUE TITLE
Css units

### ISSUE THREAD

**Issue by gruckion** [gruckion/learning#4]
- [x] When to use pixel vs em
Pixels are only good when spacing out the layout. It should not be used for fonts. If the user changes the default font-size this will not be reflected and will result in a poor reading experience.
- [x] Difference between em and rem
An EM is a unit of typography, equal to the currently specified point-size of the parent element which inherits from the browser. While rem is the root em, it is always relative to the browsers default font-size. This can change when zooming or if the user changes the default settings.

https://www.w3schools.com/cssref/css_units.asp
https://medium.com/code-better/css-units-for-font-size-px-em-rem-79f7e592bb97

**Comment by gruckion** [comment]
**em** the em is equal to the computed size of the parent element. Use em for layouts like menus where you want each sub menu to get progressively smaller.

If the font-size is not defined explicitly then the element will inherit from the parent element. The default font-size is provided by the browser.

```html
<div id="parent" class="parent">
  Parent
    <div id="outerChild" class="child">
      Outer child
      <div id="innerChild" class="child">
        Inner child
      </div>
    </div>
</div>
```

```css
.parent {
  font-size: 20px;
}
.child {
  font-size: 1.5em;
}
```

https://codepen.io/dixita0607/pen/LQNoOL

This results in 

Parent 20px
Outer child 30px
Inner child 45px.

Define the font-size in the root of your document then use em in the document its self.

**Comment by gruckion** [comment]
**rem** values are relative to the root html element, not the parent element. To avoid the pixel problem the root elements font size should be set to a percentage. Use rem when sorting out spacing (padding, margin e.t.c).

```html
<div class="main">
  <div class="app-header">Header</div>
  <div class="app">
    <div class="sidebar-menu">
      <div>Menu item 1</div>
      <div>Menu item 2</div>
      <div>Menu item 3</div>
      <div>Menu item 4</div>
    </div>
    <div class="content">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum dolores obcaecati quibusdam hic eos quod, praesentium consectetur reprehenderit facere iusto accusamus fugit quidem suscipit facilis voluptatem fuga maiores quo vel?
    </div>
  </div>
</div>
```

```scss
:root {
  font-size: 62.5%;
  body {
    margin: 0;
    // Body font size 16px
    font-size: 1.6rem;
  }
}

.main {
  .app-header {
    // Header font size 24px
    font-size: 2.4rem;
    // Header padding 8px
    padding: 0.8rem;
    background-color: lightblue;
    text-align: center;
  }
  .app {
    display: flex;
    .sidebar-menu {
      // Menu font-size 18px
      font-size: 1.8rem;
      // Menu padding 8px
      padding: 0.8rem;
      width: 20vw;
      background-color: lightgreen;
    }
    .content {
      // Content padding 8px
      padding: 0.8rem;
      background-color: pink;
      width: 80vw;
    }
  }
}
```

https://codepen.io/dixita0607/pen/OQpWJj
